apiVersion: v1
kind: Service
metadata:
  name: ptt-backend-service
  namespace: ptt
spec:
  selector:
    app: ptt-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ptt-mqtt-service
  namespace: ptt
spec:
  selector:
    app: ptt-backend
  ports:
    - name: mqtt1
      port: 1883
      targetPort: 1883
    - name: mqtt2
      port: 9001
      targetPort: 9001