apiVersion: v1
kind: Service
metadata:
  name: ptt-backend-service
spec:
  selector:
    app: ptt-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ptt-mqtt-service
spec:
  selector:
    app: ptt-mosquitto
  ports:
    - name: mqtt1
      port: 1883
      targetPort: 1883
    - name: mqtt2
      port: 9001
      targetPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: ptt-postgres-service
spec:
  selector:
    app: ptt-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
{{ if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ptt-keycloak-service
  labels:
    app: ptt-keycloak
spec:
  selector:
    app: ptt-keycloak
  ports:
  - name: http
    port: 8080
    targetPort: 8080
{{ end }}