---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ptt-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ptt-backend
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "create"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ptt-backend
roleRef:
  kind: Role
  name: ptt-backend
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ptt-backend

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ptt-backend
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ptt-backend
roleRef:
  kind: ClusterRole
  name: ptt-backend
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ptt-backend
    namespace: ptt
