FROM quay.io/quarkus/centos-quarkus-maven:21.3.2-java11 as build

USER root

RUN mkdir -p /usr/src/app

# Set the maven mirrors in the maven settings if available

RUN /usr/local/bin/entrypoint-run.sh

WORKDIR /usr/src/app

COPY pom.xml /usr/src/app/

RUN mvn install

COPY src /usr/src/app/src

CMD [ "mvn", "clean", "compile", "quarkus:dev" ]