FROM maven:3.8.6-openjdk-18 as build

USER root

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY pom.xml /usr/src/app/

RUN mvn install

COPY src /usr/src/app/src

CMD [ "mvn", "clean", "compile", "quarkus:dev" ]