apiVersion: v1
kind: PersistentVolume
metadata:
  name: ptt-postgres-volume
  namespace: ptt
  labels:
    type: local
    app: ptt-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgresql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ptt-postgres-volume-claim
  namespace: ptt
  labels:
    app: ptt-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi