image:
  repository: ghcr.io/2023-da-ptt/ptt-backend
  pullPolicy: Always
  tag: "latest"

# Wheter or not to use volumes ( for development mode set false)
volumes: true

postgres:
  host: ptt-postgres-service
  username: postgres
  password: postgres

keycloak:
  enabled: true
  username: s1mple133
  password: 4XRXmsVNvqdK8KcJ!
  hostname: https://auth.perftest.tech/

oidc:
  url: https://auth.perftest.tech/realms/master
  client:
    id: backend-service
    secret: E6Ghz9DEfTVf5Pga3aWQ6cvwDeOGxZhv